seed: 1234
batch_size: 32
lr: 1.e-4
total_steps: 100000
warmup_steps: 0
save_interval: 10000
test_interval: 10000
viz_interval: 10000
log_interval: 100

data_path: "viper_rl_data/datasets/reach_controller"
ema: 0.9999
optimizer: "adam"
lr_schedule: "constant"

image_size: 64
seq_len: 3
frame_skip: 1
ae_ckpt: "viper_rl_data/self_trained_checkpoints/reach_controller_vqgan_gpus"

n_classes: null
class_cond: false

model: "videogpt"
transformer:
  embed_dim: 256
  num_heads: 8
  num_layers: 8
  mlp_dim: 1024
  dropout: 0.1
  attention_dropout: 0.1

open_loop_ctx: 1
